apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aks-image 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aks-image 
    spec:
      containers:
        - name: aks-image 
          image: atbaggaacr.azurecr.io/aks-image 
          ports:
          - containerPort: 8080