apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name:  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  
    spec:
      containers:
        - name:  
          image: acrfromcli.azurecr.io/ 
          ports:
          - containerPort: 